version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/work
    steps:
      - checkout
      - restore_cache:
          key: v1-{{checksum "project.clj"}}
      - run: lein deps
      - save_cache:
          key: v1-{{checksum "project.clj"}}
          paths:
            - ~/.m2
      - run: lein test

  release:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/work
    steps:
      - checkout
      - restore_cache:
          key: v1-{{checksum "project.clj"}}
      - run: lein release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - request_release:
          type: approval
          requires:
            - test
      - release:
          requires:
            - request_release

